# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: npm test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    timeout-minutes: 5

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
      redis:
        image: redis:6.2
        ports:
          - 6379:6379

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os: [ubuntu-22.04]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    #- run: npm run build --if-present
    - name: Copy test configuration
      run: cp config/env/test.js_SAMPLE config/env/test.js
    - name: Run tests on ${{ matrix.os }} node ${{ matrix.node-version }}
      run: npm test
